# Generated by Django 5.2.4 on 2025-08-29 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('correo_encargado', models.EmailField(max_length=254)),
                ('esta_activo', models.BooleanField(default=True)),
                ('encargado', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='departamento_encargado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('esta_activa', models.BooleanField(default=True)),
                ('encargado', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cuadrilla_encargada', to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo_encargado', models.EmailField(max_length=254)),
                ('esta_activa', models.BooleanField(default=True)),
                ('encargado', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='direccion_encargada', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.direccion'),
        ),
    ]
