# Generated by Django 5.2.5 on 2025-11-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='encargado',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='encargado',
        ),
        migrations.DeleteModel(
            name='Cuadrilla',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
    ]
