import django
import os

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'UrbanSensor.settings')
django.setup()

from departamentos.models import Departamento
from encuestas.models import TipoIncidencia, Encuesta
from incidencias.models import Vecino, Incidencia
from cuadrillas.models import Cuadrilla
from django.contrib.auth.models import User

tipo_incidencias = [
    {"nombre": "Bache en vía pública", "descripcion": "Reporte de hundimientos o baches que afectan la circulación vehicular.", "departamento": Departamento.objects.get(nombre="Departamento de Vialidad")},
    {"nombre": "Obstrucción por escombros", "descripcion": "Material de construcción o escombros bloqueando calles o aceras.", "departamento": Departamento.objects.get(nombre="Departamento de Vialidad")},
    {"nombre": "Falla en recolección de basura", "descripcion": "Contenedores llenos o falta de recolección en la zona.", "departamento": Departamento.objects.get(nombre="Departamento de Recoleccion")},
    {"nombre": "Vertedero ilegal", "descripcion": "Acumulación de desechos en lugares no autorizados.", "departamento": Departamento.objects.get(nombre="Departamento de Recoleccion")},
    {"nombre": "Foco de insectos", "descripcion": "Aparición de criaderos de mosquitos u otros insectos.", "departamento": Departamento.objects.get(nombre="Departamento de Epidemiologia")},
    {"nombre": "Posible brote epidemiológico", "descripcion": "Reporte de síntomas colectivos que puedan indicar un brote de enfermedad.", "departamento": Departamento.objects.get(nombre="Departamento de Epidemiologia")},
    {"nombre": "Señal de tránsito dañada", "descripcion": "Señales caídas, dobladas o deterioradas.", "departamento": Departamento.objects.get(nombre="Departamento de Señalizacion")},
    {"nombre": "Semáforo fuera de servicio", "descripcion": "Semáforo sin funcionamiento o intermitente.", "departamento": Departamento.objects.get(nombre="Departamento de Señalizacion")},
    {"nombre": "Daño a infraestructura patrimonial", "descripcion": "Afectación de monumentos, esculturas u otros bienes culturales.", "departamento": Departamento.objects.get(nombre="Departamento de Patrimonio")},
    {"nombre": "Vandalismo en monumentos", "descripcion": "Pintadas o daños intencionales en patrimonio público.", "departamento": Departamento.objects.get(nombre="Departamento de Patrimonio")},
    {"nombre": "Situación de riesgo en establecimiento", "descripcion": "Condiciones que representen peligro para la seguridad.", "departamento": Departamento.objects.get(nombre="Departamento de Prevencion")},
    {"nombre": "Incumplimiento de normas de seguridad", "descripcion": "Falta de señalización de seguridad o medidas preventivas.", "departamento": Departamento.objects.get(nombre="Departamento de Prevencion")},
    {"nombre": "Proyecto urbanístico pendiente", "descripcion": "Solicitud de revisión o actualización de un proyecto urbano.", "departamento": Departamento.objects.get(nombre="Departamento de Planificacion")},
    {"nombre": "Desorden en uso de espacios públicos", "descripcion": "Ocupación indebida o cambios no planificados en espacios comunitarios.", "departamento": Departamento.objects.get(nombre="Departamento de Planificacion")},
    {"nombre": "Daño en infraestructura pública", "descripcion": "Roturas o daños en edificios, parques o estructuras públicas.", "departamento": Departamento.objects.get(nombre="Departamento de Vialidad")},
    {"nombre": "Fuga de agua en instalaciones municipales", "descripcion": "Pérdidas o filtraciones dentro de dependencias públicas.", "departamento": Departamento.objects.get(nombre="Departamento de Planificacion")},
    {"nombre": "Luminaria pública apagada", "descripcion": "Farolas apagadas o con fallas eléctricas.", "departamento": Departamento.objects.get(nombre="Departamento de Alumbrado")},
    {"nombre": "Corto circuito en alumbrado", "descripcion": "Chispas o fallas eléctricas visibles en postes o luminarias.", "departamento": Departamento.objects.get(nombre="Departamento de Alumbrado")},
    {"nombre": "Basura acumulada en vía pública", "descripcion": "Acumulación de basura en calles, parques o plazas.", "departamento": Departamento.objects.get(nombre="Departamento de Limpieza")},
    {"nombre": "Limpieza urgente requerida", "descripcion": "Derrames o situaciones que requieran limpieza inmediata.", "departamento": Departamento.objects.get(nombre="Departamento de Limpieza")}
]

for t in tipo_incidencias:
    TipoIncidencia.objects.create(**t)

encuestas = [
    {"titulo": "Evaluación de reparación de bache", 
    "descripcion": "Encuesta para evaluar la calidad de la reparación realizada en la vía afectada por el bache.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Bache en vía pública"),
    "estado": "vigente"},
    {"titulo": "Satisfacción con limpieza de escombros",
    "descripcion": "Consulta para medir la satisfacción con el retiro de escombros que obstruían el tránsito.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Obstrucción por escombros"),
    "estado": "creado"},
    {"titulo": "Encuesta sobre recolección de basura",
    "descripcion": "Encuesta para conocer si la recolección de basura volvió a ser regular.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Falla en recolección de basura"),
    "estado": "vigente"},
    {"titulo": "Control de vertederos ilegales",
    "descripcion": "Encuesta para evaluar la efectividad del retiro de desechos en zonas donde se detectó un vertedero ilegal.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Vertedero ilegal"),
    "estado": "vigente"},
    {"titulo": "Control de focos de insectos",
    "descripcion": "Formulario para confirmar si se eliminaron los criaderos de insectos reportados.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Foco de insectos"),
    "estado": "creado"},
    {"titulo": "Seguimiento de brote epidemiológico",
    "descripcion": "Encuesta para conocer la situación de salud tras la intervención por posible brote epidemiológico.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Posible brote epidemiológico"),
    "estado": "vigente"},
    {"titulo": "Revisión de señal dañada",
    "descripcion": "Encuesta para validar si la señal de tránsito dañada fue reparada correctamente.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Señal de tránsito dañada"),
    "estado": "vigente"},
    {"titulo": "Evaluación de semáforo reparado",
    "descripcion": "Formulario para verificar la satisfacción con la reparación del semáforo fuera de servicio.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Semáforo fuera de servicio"),
    "estado": "creado"},
    {"titulo": "Conservación de patrimonio público",
    "descripcion": "Encuesta para evaluar la restauración o mantenimiento del bien patrimonial afectado.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Daño a infraestructura patrimonial"),
    "estado": "vigente"},
    {"titulo": "Reporte de vandalismo en monumentos",
    "descripcion": "Formulario para evaluar la limpieza o restauración tras actos de vandalismo.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Vandalismo en monumentos"),
    "estado": "creado"},
    {"titulo": "Inspección de riesgos comunitarios",
    "descripcion": "Encuesta para validar si la situación de riesgo reportada fue atendida y mitigada.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Situación de riesgo en establecimiento"),
    "estado": "vigente"},
    {"titulo": "Cumplimiento de normas de seguridad",
    "descripcion": "Evaluación sobre la corrección de incumplimientos de normas de seguridad.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Incumplimiento de normas de seguridad"),
    "estado": "bloqueado"},
    {"titulo": "Revisión de proyecto urbanístico",
    "descripcion": "Encuesta para conocer la percepción del avance en el proyecto urbanístico pendiente.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Proyecto urbanístico pendiente"),
    "estado": "vigente"},
    {"titulo": "Ordenamiento de espacios públicos",
    "descripcion": "Formulario para evaluar el restablecimiento del orden en espacios públicos mal utilizados.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Desorden en uso de espacios públicos"),
    "estado": "creado"},
    {"titulo": "Estado de infraestructura pública",
    "descripcion": "Encuesta para verificar si los daños en infraestructura pública fueron reparados adecuadamente.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Daño en infraestructura pública"),
    "estado": "vigente"},
    {"titulo": "Control de fugas de agua",
    "descripcion": "Formulario para confirmar si la fuga de agua en instalaciones municipales fue reparada.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Fuga de agua en instalaciones municipales"),
    "estado": "creado"},
    {"titulo": "Seguimiento de luminarias apagadas",
    "descripcion": "Encuesta para evaluar si la luminaria reportada ya funciona correctamente.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Luminaria pública apagada"),
    "estado": "vigente"},
    {"titulo": "Inspección por corto eléctrico",
    "descripcion": "Formulario para obtener retroalimentación sobre la reparación de un corto circuito en alumbrado público.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Corto circuito en alumbrado"),
    "estado": "vigente"},
    {"titulo": "Satisfacción con limpieza urbana",
    "descripcion": "Encuesta para evaluar el trabajo de limpieza realizado tras la acumulación de basura.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Basura acumulada en vía pública"),
    "estado": "creado"},
    {"titulo": "Evaluación de limpieza urgente",
    "descripcion": "Formulario para verificar si la limpieza urgente fue efectiva y oportuna.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Limpieza urgente requerida"),
    "estado": "vigente"},
    {"titulo": "Verificación de nivelación vial",
    "descripcion": "Encuesta para confirmar si la intervención mejoró la nivelación del área afectada.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Bache en vía pública"),
    "estado": "creado"},
    {"titulo": "Seguimiento a despeje de caminos",
    "descripcion": "Formulario para evaluar si el despeje de escombros permitió restablecer el tránsito.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Obstrucción por escombros"),
    "estado": "vigente"},
    {"titulo": "Control de rutas de recolección",
    "descripcion": "Encuesta sobre la eficiencia de la ruta de recolección tras el incidente.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Falla en recolección de basura"),
    "estado": "bloqueado"},
    {"titulo": "Percepción de seguridad en zonas con vertederos",
    "descripcion": "Encuesta para medir si la eliminación del vertedero ilegal mejoró la seguridad.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Vertedero ilegal"),
    "estado": "creado"},
    {"titulo": "Control post-fumigación",
    "descripcion": "Formulario para confirmar la efectividad del tratamiento aplicado contra insectos.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Foco de insectos"),
    "estado": "vigente"},
    {"titulo": "Estado sanitario posterior a intervención",
    "descripcion": "Encuesta para conocer si disminuyeron los síntomas vinculados al brote.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Posible brote epidemiológico"),
    "estado": "vigente"},
    {"titulo": "Validación de visibilidad de señales",
    "descripcion": "Encuesta sobre la visibilidad y ubicación de la señalización reparada.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Señal de tránsito dañada"),
    "estado": "creado"},
    {"titulo": "Evaluación del funcionamiento del semáforo",
    "descripcion": "Formulario para comprobar que el semáforo mantiene un funcionamiento estable.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Semáforo fuera de servicio"),
    "estado": "vigente"},
    {"titulo": "Estado de restauración patrimonial",
    "descripcion": "Encuesta orientada a evaluar los trabajos de conservación realizados.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Daño a infraestructura patrimonial"),
    "estado": "vigente"},
    {"titulo": "Prevención de nuevos actos vandálicos",
    "descripcion": "Consulta sobre la percepción ciudadana frente a mejoras en seguridad en monumentos.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Vandalismo en monumentos"),
    "estado": "bloqueado"},
    {"titulo": "Percepción de mitigación de riesgos",
    "descripcion": "Encuesta para evaluar si la intervención redujo el riesgo detectado.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Situación de riesgo en establecimiento"),
    "estado": "creado"},
    {"titulo": "Evaluación de cumplimiento de protocolos",
    "descripcion": "Formulario para medir la corrección de fallas detectadas en normas de seguridad.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Incumplimiento de normas de seguridad"),
    "estado": "vigente"},
    {"titulo": "Aprobación de ajustes urbanísticos",
    "descripcion": "Encuesta sobre las modificaciones aplicadas al proyecto pendiente.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Proyecto urbanístico pendiente"),
    "estado": "creado"},
    {"titulo": "Revisión de uso ordenado de espacios públicos",
    "descripcion": "Formulario para medir si se solucionó el mal uso del espacio reportado.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Desorden en uso de espacios públicos"),
    "estado": "vigente"},
    {"titulo": "Inspección post-reparación de infraestructura",
    "descripcion": "Encuesta para validar la calidad del trabajo realizado sobre el daño reportado.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Daño en infraestructura pública"),
    "estado": "vigente"},
    {"titulo": "Reporte de estabilidad hídrica",
    "descripcion": "Formulario para evaluar si la fuga reparada no ha vuelto a presentarse.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Fuga de agua en instalaciones municipales"),
    "estado": "creado"},
    {"titulo": "Percepción de seguridad nocturna",
    "descripcion": "Encuesta para conocer si la reparación de luminarias mejoró la visibilidad nocturna.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Luminaria pública apagada"),
    "estado": "vigente"},
    {"titulo": "Control de fallas eléctricas",
    "descripcion": "Formulario para evaluar si el corto eléctrico ya no representa un peligro.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Corto circuito en alumbrado"),
    "estado": "creado"},
    {"titulo": "Evaluación de higiene en espacios públicos",
    "descripcion": "Encuesta para medir si el área afectada por basura acumulada quedó en buen estado.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Basura acumulada en vía pública"),
    "estado": "vigente"},
    {"titulo": "Validación de limpieza urgente realizada",
    "descripcion": "Formulario para verificar la rapidez y eficiencia de la intervención de limpieza urgente.",
    "tipo_incidencia": TipoIncidencia.objects.get(nombre="Limpieza urgente requerida"),
    "estado": "creado"},
]

for e in encuestas:
    Encuesta.objects.create(**e)

campo_adicional = [
    {"titulo": "¿La solución fue oportuna?", 
    "encuesta": Encuesta.objects.get(titulo="Evaluación de reparación de bache"), 
    "es_obligatoria": True},
    {"titulo": "¿El área quedó completamente despejada?", 
    "encuesta": Encuesta.objects.get(titulo="Satisfacción con limpieza de escombros"), 
    "es_obligatoria": False},
    {"titulo": "¿La recolección volvió a ser regular?", 
    "encuesta": Encuesta.objects.get(titulo="Encuesta sobre recolección de basura"), 
    "es_obligatoria": True},
    {"titulo": "¿El vertedero fue removido en su totalidad?", 
    "encuesta": Encuesta.objects.get(titulo="Control de vertederos ilegales"), 
    "es_obligatoria": True},
    {"titulo": "¿Observa aún presencia de insectos?", 
    "encuesta": Encuesta.objects.get(titulo="Control de focos de insectos"), 
    "es_obligatoria": True},
    {"titulo": "¿Ha mejorado la situación sanitaria?", 
    "encuesta": Encuesta.objects.get(titulo="Seguimiento de brote epidemiológico"), 
    "es_obligatoria": True},
    {"titulo": "¿La señal es visible desde todos los ángulos?", 
    "encuesta": Encuesta.objects.get(titulo="Revisión de señal dañada"), 
    "es_obligatoria": False},
    {"titulo": "¿El semáforo funciona sin interrupciones?", 
    "encuesta": Encuesta.objects.get(titulo="Evaluación de semáforo reparado"), 
    "es_obligatoria": True},
    {"titulo": "¿La restauración respeta la integridad patrimonial?", 
    "encuesta": Encuesta.objects.get(titulo="Conservación de patrimonio público"), 
    "es_obligatoria": False},
    {"titulo": "¿Se han reducido los actos vandálicos recientes?", 
    "encuesta": Encuesta.objects.get(titulo="Reporte de vandalismo en monumentos"), 
    "es_obligatoria": False},
    {"titulo": "¿El riesgo reportado fue completamente mitigado?", 
    "encuesta": Encuesta.objects.get(titulo="Inspección de riesgos comunitarios"), 
    "es_obligatoria": True},
    {"titulo": "¿Las normas de seguridad ahora se cumplen adecuadamente?", 
    "encuesta": Encuesta.objects.get(titulo="Cumplimiento de normas de seguridad"), 
    "es_obligatoria": True},
    {"titulo": "¿Percibe avances en el proyecto urbanístico?", 
    "encuesta": Encuesta.objects.get(titulo="Revisión de proyecto urbanístico"), 
    "es_obligatoria": False},
    {"titulo": "¿El espacio público está siendo utilizado correctamente?", 
    "encuesta": Encuesta.objects.get(titulo="Ordenamiento de espacios públicos"), 
    "es_obligatoria": True},
    {"titulo": "¿La infraestructura reparada parece estable?", 
    "encuesta": Encuesta.objects.get(titulo="Estado de infraestructura pública"), 
    "es_obligatoria": True},
    {"titulo": "¿Ha vuelto a notar fugas de agua?", 
    "encuesta": Encuesta.objects.get(titulo="Control de fugas de agua"), 
    "es_obligatoria": True},
    {"titulo": "¿La iluminación nocturna ha mejorado?", 
    "encuesta": Encuesta.objects.get(titulo="Seguimiento de luminarias apagadas"), 
    "es_obligatoria": False},
    {"titulo": "¿El corto eléctrico ya no representa peligro?", 
    "encuesta": Encuesta.objects.get(titulo="Inspección por corto eléctrico"), 
    "es_obligatoria": True},
    {"titulo": "¿El área quedó limpia después de la intervención?", 
    "encuesta": Encuesta.objects.get(titulo="Satisfacción con limpieza urbana"), 
    "es_obligatoria": True},
    {"titulo": "¿La limpieza urgente fue realizada en el tiempo adecuado?", 
    "encuesta": Encuesta.objects.get(titulo="Evaluación de limpieza urgente"), 
    "es_obligatoria": True},
]

incidencias = [
    {"encuesta": Encuesta.objects.get(titulo="Evaluación de reparación de bache"),
    # "vecino": Vecino.objects.get(rut="12543829-4"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user1"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 3").first(),
    "descripcion": "Bache profundo que afecta el tránsito en avenida principal.",
    "latitud": -33.452, "longitud": -70.665,
    "direccion_textual": "Av. Central 1450",
    "estado": "abierta", "prioridad": "alta"},
    {"encuesta": Encuesta.objects.get(titulo="Satisfacción con limpieza de escombros"),
    # "vecino": Vecino.objects.get(rut="17654982-1"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user2"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 7").first(),
    "descripcion": "Restos de construcción bloqueando el paso peatonal.",
    "latitud": -33.460, "longitud": -70.680,
    "direccion_textual": "Calle Olmos 322",
    "estado": "derivada", "prioridad": "normal"},
    {"encuesta": Encuesta.objects.get(titulo="Encuesta sobre recolección de basura"),
    # "vecino": Vecino.objects.get(rut="15432987-6"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user3"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 1").first(),
    "descripcion": "Contenedores desbordados durante dos días consecutivos.",
    "latitud": -33.470, "longitud": -70.672,
    "direccion_textual": "Pasaje Río Claro 55",
    "estado": "proceso", "prioridad": "alta"},
    {"encuesta": Encuesta.objects.get(titulo="Control de vertederos ilegales"),
    # "vecino": Vecino.objects.get(rut="19874325-5"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user3"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 12").first(),
    "descripcion": "Acumulación de desechos en sitio eriazo.",
    "latitud": -33.448, "longitud": -70.700,
    "direccion_textual": "Camino La Montaña 2300",
    "estado": "abierta", "prioridad": "alta"},
    {"encuesta": Encuesta.objects.get(titulo="Control de focos de insectos"),
    # "vecino": Vecino.objects.get(rut="16789423-0"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user1"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 8").first(),
    "descripcion": "Posible criadero de mosquitos cerca de canal de aguas lluvias.",
    "latitud": -33.455, "longitud": -70.650,
    "direccion_textual": "Canal del Sol 102",
    "estado": "proceso", "prioridad": "normal"},
    {"encuesta": Encuesta.objects.get(titulo="Seguimiento de brote epidemiológico"),
    # "vecino": Vecino.objects.get(rut="13456289-3"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user3"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 5").first(),
    "descripcion": "Varios vecinos reportan síntomas gastrointestinales.",
    "latitud": -33.468, "longitud": -70.640,
    "direccion_textual": "Los Nogales 955",
    "estado": "finalizada", "prioridad": "alta"},
    {"encuesta": Encuesta.objects.get(titulo="Revisión de señal dañada"),
    # "vecino": Vecino.objects.get(rut="14328956-7"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user2"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 10").first(),
    "descripcion": "Señal de pare caída en cruce peligroso.",
    "latitud": -33.490, "longitud": -70.645,
    "direccion_textual": "Calle del Cerro 74",
    "estado": "abierta", "prioridad": "normal"},
    {"encuesta": Encuesta.objects.get(titulo="Evaluación de semáforo reparado"),
    # "vecino": Vecino.objects.get(rut="12894567-2"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user3"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 9").first(),
    "descripcion": "Semáforo intermitente en horario punta.",
    "latitud": -33.460, "longitud": -70.612,
    "direccion_textual": "Av. España 890",
    "estado": "rechazada", "prioridad": "alta"},
    {"encuesta": Encuesta.objects.get(titulo="Conservación de patrimonio público"),
    # "vecino": Vecino.objects.get(rut="17654321-8"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user1"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 2").first(),
    "descripcion": "Escultura con desprendimiento de material.",
    "latitud": -33.501, "longitud": -70.620,
    "direccion_textual": "Plaza Mayor",
    "estado": "proceso", "prioridad": "normal"},
    {"encuesta": Encuesta.objects.get(titulo="Reporte de vandalismo en monumentos"),
    # "vecino": Vecino.objects.get(rut="16432978-1"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user2"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 14").first(),
    "descripcion": "Pintadas en monumento histórico.",
    "latitud": -33.420, "longitud": -70.630,
    "direccion_textual": "Rotonda del Parque",
    "estado": "abierta", "prioridad": "baja"},
    {"encuesta": Encuesta.objects.get(titulo="Inspección de riesgos comunitarios"),
    # "vecino": Vecino.objects.get(rut="15498234-6"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user3"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 6").first(),
    "descripcion": "Cableado suelto en sector residencial.",
    "latitud": -33.475, "longitud": -70.671,
    "direccion_textual": "Calle Los Pinos 442",
    "estado": "derivada", "prioridad": "alta"},
    {"encuesta": Encuesta.objects.get(titulo="Cumplimiento de normas de seguridad"),
    # "vecino": Vecino.objects.get(rut="11982345-5"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user3"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 11").first(),
    "descripcion": "Falta de barandas en obra pública.",
    "latitud": -33.465, "longitud": -70.655,
    "direccion_textual": "Av. Ossa 1332",
    "estado": "proceso", "prioridad": "normal"},
    {"encuesta": Encuesta.objects.get(titulo="Revisión de proyecto urbanístico"),
    # "vecino": Vecino.objects.get(rut="14589342-7"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user1"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 13").first(),
    "descripcion": "Consulta sobre retraso en ejecución de proyecto.",
    "latitud": -33.478, "longitud": -70.690,
    "direccion_textual": "Sector Norte, Callejón 5",
    "estado": "cerrada", "prioridad": "normal"},
    {"encuesta": Encuesta.objects.get(titulo="Ordenamiento de espacios públicos"),
    # "vecino": Vecino.objects.get(rut="13894522-1"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user2"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 4").first(),
    "descripcion": "Puestos ilegales ocupando vereda.",
    "latitud": -33.450, "longitud": -70.640,
    "direccion_textual": "Paseo Comercio 120",
    "estado": "abierta", "prioridad": "baja"},
    {"encuesta": Encuesta.objects.get(titulo="Estado de infraestructura pública"),
    # "vecino": Vecino.objects.get(rut="18345219-3"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user3"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 19").first(),
    "descripcion": "Baranda metálica dañada en puente peatonal.",
    "latitud": -33.510, "longitud": -70.670,
    "direccion_textual": "Puente Las Flores",
    "estado": "finalizada", "prioridad": "alta"},
    {"encuesta": Encuesta.objects.get(titulo="Control de fugas de agua"),
    # "vecino": Vecino.objects.get(rut="19876234-0"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user3"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 18").first(),
    "descripcion": "Fuga de agua en grifo público.",
    "latitud": -33.455, "longitud": -70.642,
    "direccion_textual": "Av. Matta 566",
    "estado": "proceso", "prioridad": "normal"},
    {"encuesta": Encuesta.objects.get(titulo="Seguimiento de luminarias apagadas"),
    # "vecino": Vecino.objects.get(rut="17234567-4"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user1"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 15").first(),
    "descripcion": "Farolas apagadas en pasaje residencial.",
    "latitud": -33.465, "longitud": -70.630,
    "direccion_textual": "Pasaje Los Cerezos 22",
    "estado": "abierta", "prioridad": "normal"},
    {"encuesta": Encuesta.objects.get(titulo="Inspección por corto eléctrico"),
    # "vecino": Vecino.objects.get(rut="16543287-9"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user2"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 20").first(),
    "descripcion": "Chispas visibles en poste antiguo.",
    "latitud": -33.470, "longitud": -70.620,
    "direccion_textual": "Calle Sur 540",
    "estado": "derivada", "prioridad": "alta"},
    {"encuesta": Encuesta.objects.get(titulo="Satisfacción con limpieza urbana"),
    # "vecino": Vecino.objects.get(rut="14326789-3"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user3"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 17").first(),
    "descripcion": "Acumulación de basura cerca de cancha deportiva.",
    "latitud": -33.480, "longitud": -70.665,
    "direccion_textual": "Cancha El Sol",
    "estado": "finalizada", "prioridad": "normal"},
    {"encuesta": Encuesta.objects.get(titulo="Evaluación de limpieza urgente"),
    # "vecino": Vecino.objects.get(rut="12983456-1"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user3"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 16").first(),
    "descripcion": "Derrame de basura por animales callejeros.",
    "latitud": -33.451, "longitud": -70.675,
    "direccion_textual": "Av. Los Álamos 900",
    "estado": "cerrada", "prioridad": "alta"},
    {"encuesta": Encuesta.objects.get(titulo="Verificación de nivelación vial"),
    # "vecino": Vecino.objects.get(rut="17894562-5"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user2"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 4").first(),
    "descripcion": "Sector presenta desnivel tras reparación previa.",
    "latitud": -33.445, "longitud": -70.670,
    "direccion_textual": "Calle Lomas 890",
    "estado": "abierta", "prioridad": "normal"},
    {"encuesta": Encuesta.objects.get(titulo="Seguimiento a despeje de caminos"),
    # "vecino": Vecino.objects.get(rut="16543987-2"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user1"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 15").first(),
    "descripcion": "Restos de árboles impiden circulación tras viento fuerte.",
    "latitud": -33.462, "longitud": -70.680,
    "direccion_textual": "Camino Viejo 221",
    "estado": "derivada", "prioridad": "alta"},
    {"encuesta": Encuesta.objects.get(titulo="Control de rutas de recolección"),
    # "vecino": Vecino.objects.get(rut="13254987-6"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user3"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 19").first(),
    "descripcion": "Camión no pasó por segunda semana en el sector.",
    "latitud": -33.499, "longitud": -70.640,
    "direccion_textual": "Av. Esmeralda 401",
    "estado": "proceso", "prioridad": "normal"},
    {"encuesta": Encuesta.objects.get(titulo="Percepción de seguridad en zonas con vertederos"),
    # "vecino": Vecino.objects.get(rut="18945321-4"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user3"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 8").first(),
    "descripcion": "Basura acumulada genera malos olores y vectores.",
    "latitud": -33.510, "longitud": -70.675,
    "direccion_textual": "Sector Las Torres",
    "estado": "abierta", "prioridad": "baja"},
    {"encuesta": Encuesta.objects.get(titulo="Control post-fumigación"),
    # "vecino": Vecino.objects.get(rut="17854326-7"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user2"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 6").first(),
    "descripcion": "Fumigación se realizó pero aún se observan insectos.",
    "latitud": -33.423, "longitud": -70.630,
    "direccion_textual": "Calle Azul 123",
    "estado": "rechazada", "prioridad": "alta"},
    {"encuesta": Encuesta.objects.get(titulo="Estado sanitario posterior a intervención"),
    # "vecino": Vecino.objects.get(rut="14456892-8"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user1"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 3").first(),
    "descripcion": "Situación sanitaria mejoró pero persisten malos olores.",
    "latitud": -33.490, "longitud": -70.610,
    "direccion_textual": "Pasaje Estrella 85",
    "estado": "proceso", "prioridad": "alta"},
    {"encuesta": Encuesta.objects.get(titulo="Validación de visibilidad de señales"),
    # "vecino": Vecino.objects.get(rut="15347652-9"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user3"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 7").first(),
    "descripcion": "Árbol tapa señal recién instalada.",
    "latitud": -33.447, "longitud": -70.662,
    "direccion_textual": "Av. Norte 200",
    "estado": "abierta", "prioridad": "normal"},
    {"encuesta": Encuesta.objects.get(titulo="Evaluación del funcionamiento del semáforo"),
    # "vecino": Vecino.objects.get(rut="12234567-5"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user3"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 13").first(),
    "descripcion": "Semáforo funciona, pero los tiempos no son adecuados.",
    "latitud": -33.440, "longitud": -70.651,
    "direccion_textual": "Cruce San Miguel",
    "estado": "derivada", "prioridad": "alta"},
    {"encuesta": Encuesta.objects.get(titulo="Estado de restauración patrimonial"),
    # "vecino": Vecino.objects.get(rut="18876543-1"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user2"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 11").first(),
    "descripcion": "Placa informativa dañada junto al monumento reparado.",
    "latitud": -33.455, "longitud": -70.605,
    "direccion_textual": "Plaza Sur",
    "estado": "finalizada", "prioridad": "normal"},
    {"encuesta": Encuesta.objects.get(titulo="Prevención de nuevos actos vandálicos"),
    # "vecino": Vecino.objects.get(rut="16543821-0"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user1"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 9").first(),
    "descripcion": "Nuevo rayado detectado en la base del monumento.",
    "latitud": -33.476, "longitud": -70.661,
    "direccion_textual": "Boulevard Central",
    "estado": "abierta", "prioridad": "baja"},
    {"encuesta": Encuesta.objects.get(titulo="Percepción de mitigación de riesgos"),
    # "vecino": Vecino.objects.get(rut="14583921-9"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user3"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 2").first(),
    "descripcion": "Escalera pública continúa resbalosa tras intervención.",
    "latitud": -33.499, "longitud": -70.673,
    "direccion_textual": "Callejón 12",
    "estado": "proceso", "prioridad": "alta"},
    {"encuesta": Encuesta.objects.get(titulo="Evaluación de cumplimiento de protocolos"),
    # "vecino": Vecino.objects.get(rut="17894532-5"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user3"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 10").first(),
    "descripcion": "Barreras de seguridad insuficientes en obra pública.",
    "latitud": -33.421, "longitud": -70.600,
    "direccion_textual": "Av. Libertad 1880",
    "estado": "abierta", "prioridad": "normal"},
    {"encuesta": Encuesta.objects.get(titulo="Aprobación de ajustes urbanísticos"),
    # "vecino": Vecino.objects.get(rut="15649823-4"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user2"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 17").first(),
    "descripcion": "Obra presenta modificaciones no anunciadas.",
    "latitud": -33.468, "longitud": -70.612,
    "direccion_textual": "Nuevo Barrio Central",
    "estado": "derivada", "prioridad": "normal"},
    {"encuesta": Encuesta.objects.get(titulo="Revisión de uso ordenado de espacios públicos"),
    # "vecino": Vecino.objects.get(rut="11234567-8"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user1"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 20").first(),
    "descripcion": "Puestos informales volvieron a instalarse.",
    "latitud": -33.460, "longitud": -70.645,
    "direccion_textual": "Paseo Verde",
    "estado": "rechazada", "prioridad": "baja"},
    {"encuesta": Encuesta.objects.get(titulo="Inspección post-reparación de infraestructura"),
    # "vecino": Vecino.objects.get(rut="17543289-0"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user3"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 1").first(),
    "descripcion": "La baranda reparada presenta filtración de óxido.",
    "latitud": -33.420, "longitud": -70.635,
    "direccion_textual": "Puente Viejo",
    "estado": "cerrada", "prioridad": "alta"},
    {"encuesta": Encuesta.objects.get(titulo="Reporte de estabilidad hídrica"),
    # "vecino": Vecino.objects.get(rut="14398765-2"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user3"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 5").first(),
    "descripcion": "Nueva filtración lateral en la cañería reparada.",
    "latitud": -33.430, "longitud": -70.674,
    "direccion_textual": "Calle Río Claro",
    "estado": "proceso", "prioridad": "normal"},
    {"encuesta": Encuesta.objects.get(titulo="Percepción de seguridad nocturna"),
    # "vecino": Vecino.objects.get(rut="16654321-9"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user1"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 18").first(),
    "descripcion": "Un poste quedó sin luz en la misma cuadra.",
    "latitud": -33.480, "longitud": -70.632,
    "direccion_textual": "Pasaje El Lucero 90",
    "estado": "abierta", "prioridad": "normal"},
    {"encuesta": Encuesta.objects.get(titulo="Control de fallas eléctricas"),
    # "vecino": Vecino.objects.get(rut="18234567-3"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user2"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 16").first(),
    "descripcion": "Corto eléctrico en poste provoca chispas nocturnas.",
    "latitud": -33.475, "longitud": -70.600,
    "direccion_textual": "Calle Aurora 701",
    "estado": "finalizada", "prioridad": "alta"},
    {"encuesta": Encuesta.objects.get(titulo="Evaluación de higiene en espacios públicos"),
    # "vecino": Vecino.objects.get(rut="18765432-5"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user3"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 14").first(),
    "descripcion": "Acumulación persistente de basura en plaza recreativa.",
    "latitud": -33.450, "longitud": -70.690,
    "direccion_textual": "Plaza Los Aromos",
    "estado": "abierta", "prioridad": "normal"},
    {"encuesta": Encuesta.objects.get(titulo="Validación de limpieza urgente realizada"),
    # "vecino": Vecino.objects.get(rut="19834567-8"),
    "territorial": User.objects.filter(groups__name="Territorial").get(username="territorial_user3"),
    "cuadrilla": Cuadrilla.objects.filter(nombre__startswith="Cuadrilla 12").first(),
    "descripcion": "Derrame de residuos orgánicos requiere segunda limpieza.",
    "latitud": -33.465, "longitud": -70.668,
    "direccion_textual": "Pasaje Sur 33",
    "estado": "proceso", "prioridad": "alta"},
]

# Ahora, antes de crear las Incidencias, determinamos la cuadrilla correcta por departamento de la encuesta
for i in incidencias:
    encuesta = i.get("encuesta")
    cuadrilla_obj = None
    if encuesta and getattr(encuesta, 'tipo_incidencia', None):
        departamento = encuesta.tipo_incidencia.departamento
        if departamento:
            cuadrilla_obj = Cuadrilla.objects.filter(departamento=departamento, esta_activa=True).first()
    # asignamos la cuadrilla sólo si pertenece al departamento de la encuesta
    i["cuadrilla"] = cuadrilla_obj

for i in incidencias:
    Incidencia.objects.create(**i)