# Generated by Django 5.2.4 on 2025-10-08 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo_encargado', models.EmailField(max_length=254)),
                ('esta_activa', models.BooleanField(default=True)),
                ('encargado', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='direccion_encargada', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
