# Generated by Django 5.2.4 on 2025-09-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_profile_telefono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username'], 'permissions': [('can_block_user', 'Puede bloquear usuarios')]},
        ),
    ]
