# Generated by Django 5.2.4 on 2025-08-29 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=400)),
                ('estado', models.CharField(choices=[('creado', 'Creado'), ('vigente', 'Vigente'), ('bloqueado', 'Bloqueado')], default='creado', max_length=10)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('normal', 'Normal'), ('baja', 'Baja')], default='normal', max_length=10)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='CamposAdicionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('orden', models.IntegerField()),
                ('es_obligatoria', models.BooleanField(default=False)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('direccion_textual', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('derivada', 'Derivada'), ('proceso', 'Proceso'), ('finalizada', 'Finalizada'), ('cerrada', 'Cerrada'), ('rechazada', 'Rechazada')], default='abierta', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.cuadrilla')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidencias.encuesta')),
                ('territorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_territorial', to=settings.AUTH_USER_MODEL)),
                ('vecino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='incidencias.vecino')),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='evidencias/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.incidencia')),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.camposadicionales')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.incidencia')),
            ],
        ),
        migrations.CreateModel(
            name='TipoIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='encuesta',
            name='tipo_incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidencias.tipoincidencia'),
        ),
    ]
