# Generated by Django 5.2.4 on 2025-11-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('normal', 'Normal'), ('baja', 'Baja')], default='normal', max_length=10),
        ),
    ]
