# Generated by Django 5.2.7 on 2025-10-30 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
        ('direcciones', '0001_initial'),
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='departamentos.departamento'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='direcciones.direccion'),
        ),
    ]
