# Generated by Django 5.2.4 on 2025-11-21 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
        ('incidencias', '0002_incidencia_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='destinatario_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_destino', to='departamentos.departamento'),
        ),
    ]
