# Generated by Django 5.2.5 on 2025-10-30 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_incidencia_departamento_incidencia_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='direccion',
        ),
    ]
