# Generated by Django 5.2.5 on 2025-11-14 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_tipoincidencia_remove_encuestarespuesta_incidencia_and_more'),
        ('incidencias', '0002_alter_incidencia_cuadrilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tipoincidencia',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='evidencia',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='EncuestaRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField()),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.incidencia')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.camposadicionales')),
            ],
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='vecino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='incidencias.vecino'),
        ),
    ]
