# Generated by Django 5.2.5 on 2025-11-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0004_delete_vecino_remove_encuesta_departamento_and_more'),
        ('incidencias', '0003_vecino_remove_tipoincidencia_departamento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoIncidencia',
        ),
    ]
