# Generated by Django 5.2.5 on 2025-11-22 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_incidencia_destinatario_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='destinatario_departamento',
        ),
    ]
