# Generated by Django 5.2.4 on 2025-08-20 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(blank=True, max_length=240, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=240, null=True)),
                ('state', models.CharField(blank=True, default='Activo', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['habilidad'],
            },
        ),
        migrations.CreateModel(
            name='Heroe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_heroe', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, default='Activo', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes.habilidad')),
            ],
            options={
                'verbose_name': 'Heroe',
                'verbose_name_plural': 'Heroes',
                'ordering': ['nombre_heroe'],
            },
        ),
    ]
