# Generated by Django 5.2.4 on 2025-10-08 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamposAdicionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('orden', models.IntegerField()),
                ('es_obligatoria', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=400)),
                ('estado', models.CharField(choices=[('creado', 'Creado'), ('vigente', 'Vigente'), ('bloqueado', 'Bloqueado')], default='creado', max_length=10)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('normal', 'Normal'), ('baja', 'Baja')], default='normal', max_length=10)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamentos.departamento')),
            ],
        ),
    ]
