# Generated by Django 5.2.4 on 2025-11-24 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=400)),
                ('estado', models.CharField(choices=[('creado', 'Creado'), ('vigente', 'Vigente'), ('bloqueado', 'Bloqueado')], default='creado', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CamposAdicionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('orden', models.IntegerField()),
                ('es_obligatoria', models.BooleanField(default=False)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='TipoIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamentos.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='encuesta',
            name='tipo_incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encuestas.tipoincidencia'),
        ),
    ]
