# Generated by Django 5.2.4 on 2025-10-08 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encuestas', '0001_initial'),
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='tipo_incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidencias.tipoincidencia'),
        ),
        migrations.AddField(
            model_name='camposadicionales',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.encuesta'),
        ),
        migrations.AddField(
            model_name='encuestarespuesta',
            name='incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.incidencia'),
        ),
        migrations.AddField(
            model_name='encuestarespuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.camposadicionales'),
        ),
    ]
