# Generated by Django 5.2.5 on 2025-11-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='encuestarespuesta',
            name='incidencia',
        ),
        migrations.RemoveField(
            model_name='encuestarespuesta',
            name='pregunta',
        ),
    ]
