# Generated by Django 5.2.5 on 2025-11-14 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_remove_departamento_correo_encargado'),
        ('encuestas', '0003_tipoincidencia_remove_encuestarespuesta_incidencia_and_more'),
        ('incidencias', '0003_vecino_remove_tipoincidencia_departamento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vecino',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='departamento',
        ),
        migrations.AddField(
            model_name='tipoincidencia',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamentos.departamento'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='tipo_incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encuestas.tipoincidencia'),
        ),
        migrations.DeleteModel(
            name='EncuestaRespuesta',
        ),
    ]
