# Generated by Django 5.2.4 on 2025-11-18 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direcciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('esta_activo', models.BooleanField(default=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='direcciones.direccion')),
                ('encargado', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='departamento_encargado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
