# Generated by Django 5.2.5 on 2025-11-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='correo_encargado',
        ),
    ]
